name: Manual Asset & Readme Update
on:
  workflow_dispatch: # This creates the manual button

jobs:
  update:
    name: Update Assets/Readme
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Assets and Readme
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        ASSETS_DIR: assets   # <--- ADD THIS LINE
